#!/usr/bin/env ruby
# frozen_string_literal: true

require "json"

out = { args: ARGV, pwd: Dir.pwd }
out.merge! env: ENV.to_h unless ARGV.include? "--fail"

puts(out.to_json)
warn({ stderr: true }.to_json)

exit(1) if ARGV.include? "--fail"
