AllCops:
  TargetRubyVersion: 2.6
  NewCops: enable

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/ParameterLists:
  Enabled: false

Style/StringLiterals:
  Enabled: true
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  Enabled: true
  EnforcedStyle: double_quotes

Layout/LineLength:
  Max: 120
  Exclude:
    - plugin_kit.gemspec

Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Lint/RescueException:
  Exclude:
    - lib/cocov/plugin_kit.rb
